### ISSUE TITLE
the add method give java null pointer exception

### ISSUE THREAD

**Issue by babu3009** [UltimaPhoenix/openfire-roomservice-plugin#1]
the java null pointer exception seems to be a bug, can you help fixing this issue ?

**Comment by UltimaPhoenix** [comment]
Please specify what are your parameters and the stack trace. Remember that parameters are: "type", "secret", "jid", "subdomain", "roomName".

**Comment by babu3009** [comment]
type = add
secret = password
jid = joe.htc%40chat1%2Fchat1
roomName= general

not so sure of how to get the stack trace but the xml output gives java null pointer exception

let me know if there is a way to take the stacktrace, sorry i am very new to java.

**Comment by UltimaPhoenix** [comment]
You need to specify the "subdomain" parameter.

**Comment by babu3009** [comment]
sorry about earlier msg i missed adding subdoman.

http://10.10.1.32:9090/plugins/roomService/roomservice?type=add&roomName=room&subdomain=coco.chat1&secret=ESbSemyLQ@Gk9CxwGmC&jid=john.my-group-name@chat1/chat1

is the actual url on which i am performing http get.

**Comment by UltimaPhoenix** [comment]
Sorry for editing; I need to edit the plugin to check in depth your issue.

Can you try this url? http://10.10.1.32:9090/plugins/roomService/roomservice?type=add&roomName=room&subdomain=coco.chat1&secret=ESbSemyLQ@Gk9CxwGmC&jid=john.my-group-name@chat1

PS. Did you configure the plugin in Openfire admin console?

**Comment by babu3009** [comment]
the url you gave has subdomain = "coco.chat1" , which should be actually "coco" (all without quotes).

please check my fork i have added another method https://github.com/babu3009/roomservice/commit/1c10b09d58687584153f0cc775010b5d6b5dc561 for the diff. that works, i have updated the readme also. thanks for your help.
